version: '3.9'

services:
  mongodb:
    image: mongo
    container_name: review_mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=youreview
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=changemeinprod!
    volumes:
      - mongo:/data
    networks:
      - youreview
  
  mongo-express:
    image: mongo-express
    container_name: mongo_express
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=changemeinprod!
      - ME_CONFIG_MONGODB_SERVER=mongodb
    networks:
      - youreview

volumes:
  mongo: {}

networks:
  youreview:
    driver: bridge